### ISSUE TITLE
a problem and errors api_key

### ISSUE THREAD

**Issue by PedramChegini** [muhammedAnjoom/netflix-clone#1]
there is a problem :
import 'package:netflix_clone/infrastructure/api_key.dart';
is missed on the project.
how can I solve that?

**Comment by muhammedAnjoom** [comment]
add your own api key in themoviedb.org

**Comment by ecorbero** [comment]
Just in case you did not understand the instructions, do the following:

- Add a file named  'api_key.dart' in the 'infrastructure' directory.
- Add this line, and nothing else, in the api_key.dart'  file: 
 `const apiKey = "YOUR_THEMOVIEDB_APIKEY";`

PS: Great job Muhammed .Loved your code!

**Comment by PedramChegini** [comment]
I got it. I did that. No problem
